### ISSUE TITLE
Mac Test Issue

### ISSUE THREAD

**Issue by OsakaSecond** [asdwastakenig/issues.rep#1]
Cant run the Unit Tests on Mac.

Platform: Mac

Sample: pre-samples

pls fix 

software: CLOSED SOURCE UNIT TEST HELPER

**Comment by asdwastakenig** [comment]
hello osakaSecond(lol we have same name), nope, no mac support

**Comment by OsakaSecond** [comment]
fuck you

**Comment by asdwastakenig** [comment]
love you too

**Comment by OsakaSecond** [comment]
hey

**Comment by OsakaSecond** [comment]
fuck you
